package view;

import connection.LoadData;
import connection.UpdateData;
import controller.Controller;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import static javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE;
import javax.swing.table.DefaultTableModel;
import model.HoaDon;
import model.NhanVien;
import model.TaiKhoan;
import model.Ve;

/**
 *
 * @author tuanbuiquoc
 */
public class GiaoDienQuanLyNhanVien extends javax.swing.JFrame {

    /**
     * Creates new form GiaoDienQuanLyNhanVien
     */
    private String sdtNhanVien = "";
    private String maHoaDon = "";

    DefaultTableModel dtmNhanVien = null;
    DefaultTableModel dtmHoaDon = null;
    DefaultTableModel dtmVe = null;

    public GiaoDienQuanLyNhanVien() {
        initComponents();
        jButton_QuayLai.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        jButton_KhoiPhucMK.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        jButton_SuaNhanVien.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        jButton_ThemNhanVien.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        jButton_XoaNhanVien.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        dtmHoaDon = (DefaultTableModel) jTable_HoaDon.getModel();
        dtmHoaDon.setColumnIdentifiers(new Object[]{
            "Mã HĐ", "SĐT KH", "Ngày Xuất", "Thanh Toán", "Tổng", "SĐT NV"
        });

        dtmVe = (DefaultTableModel) jTable_Ve.getModel();
        dtmVe.setColumnIdentifiers(new Object[]{
            "Mã Vé", "Mã CB", "Giá", "Ký Gửi",
            "CMND Người Bay", "Tên Người Bay", "Ngày Sinh", "Mã HĐ", "Mã Ghế"
        });

        dtmNhanVien = (DefaultTableModel) jTable_NhanVien.getModel();
        dtmNhanVien.setColumnIdentifiers(new Object[]{
            "SĐT NV", "Tên NV"
        });
        loadBangNhanVien();

        this.addWindowListener(new WindowAdapter() {
            public void windowClosing(WindowEvent e) {
                int confirmed = JOptionPane.showConfirmDialog(null,
                        "Bạn có chắc muốn thoát chương trình không?", "Xác nhận",
                        JOptionPane.YES_NO_OPTION);

                if (confirmed == JOptionPane.YES_OPTION) {
                    dispose();
                } else {
                    setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
                }
            }
        });
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);
        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel_IconMayBay = new javax.swing.JLabel();
        jLabel_HPT = new javax.swing.JLabel();
        jLabel_AirLines = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_HoaDon = new javax.swing.JTable(){
            public boolean isCellEditable(int row, int column){
                return false;
            }};
            jScrollPane2 = new javax.swing.JScrollPane();
            jTable_NhanVien = new javax.swing.JTable(){
                public boolean isCellEditable(int row, int column){
                    return false;
                }
            };
            jScrollPane3 = new javax.swing.JScrollPane();
            jTable_Ve = new javax.swing.JTable(){
                public boolean isCellEditable(int row, int column){
                    return false;
                }
            };
            jSeparator1 = new javax.swing.JSeparator();
            jLabel1 = new javax.swing.JLabel();
            jLabel2 = new javax.swing.JLabel();
            jLabel3 = new javax.swing.JLabel();
            jLabel4 = new javax.swing.JLabel();
            jTextField_SDTNhanVien = new javax.swing.JTextField();
            jLabel5 = new javax.swing.JLabel();
            jTextField_TenNhanVien = new javax.swing.JTextField();
            jButton_QuayLai = new javax.swing.JButton();
            jSeparator2 = new javax.swing.JSeparator();
            jSeparator3 = new javax.swing.JSeparator();
            jSeparator4 = new javax.swing.JSeparator();
            jLabel9 = new javax.swing.JLabel();
            jSeparator5 = new javax.swing.JSeparator();
            jTextField_TimKiem = new javax.swing.JTextField();
            jButton_ThemNhanVien = new javax.swing.JButton();
            jButton_XoaNhanVien = new javax.swing.JButton();
            jLabel6 = new javax.swing.JLabel();
            jLabel7 = new javax.swing.JLabel();
            jLabel_CMND = new javax.swing.JLabel();
            jTextField_DiaChi = new javax.swing.JTextField();
            jTextField_TenDangNhap = new javax.swing.JTextField();
            jTextField_CMND = new javax.swing.JTextField();
            jButton_SuaNhanVien = new javax.swing.JButton();
            jLabel_BaoLoi = new javax.swing.JLabel();
            jCheckBox_HoaDonDaThanhToan = new javax.swing.JCheckBox();
            jLabel10 = new javax.swing.JLabel();
            jLabel_PhanQuyen = new javax.swing.JLabel();
            jComboBox_PhanQuyen = new javax.swing.JComboBox<>();
            jButton_KhoiPhucMK = new javax.swing.JButton();

            setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
            setTitle("Quản lý nhân viên");

            jPanel1.setBackground(new java.awt.Color(48, 57, 82));
            jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

            jLabel_IconMayBay.setForeground(new java.awt.Color(204, 255, 255));
            jLabel_IconMayBay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/images/icons8_airplane_48px_4.png"))); // NOI18N

            jLabel_HPT.setFont(new java.awt.Font("Roboto Mono Light", 1, 48)); // NOI18N
            jLabel_HPT.setForeground(new java.awt.Color(255, 255, 255));
            jLabel_HPT.setText("HPT");

            jLabel_AirLines.setFont(new java.awt.Font("Roboto Light", 1, 24)); // NOI18N
            jLabel_AirLines.setForeground(new java.awt.Color(255, 255, 255));
            jLabel_AirLines.setText("AIRLINES™");

            javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
            jPanel1.setLayout(jPanel1Layout);
            jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(27, 27, 27)
                    .addComponent(jLabel_IconMayBay)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jLabel_HPT)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabel_AirLines, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );
            jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_HPT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel_AirLines, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel_IconMayBay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );

            jPanel2.setBackground(new java.awt.Color(89, 98, 117));
            jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
            jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mousePressed(java.awt.event.MouseEvent evt) {
                    jPanel2MousePressed(evt);
                }
            });

            jTable_HoaDon.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
            jTable_HoaDon.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {

                },
                new String [] {
                    "Title 1", "Title 2", "Title 3", "Title 4"
                }
            ));
            jTable_HoaDon.setRowHeight(25);
            jTable_HoaDon.setRowMargin(2);
            jTable_HoaDon.setSelectionBackground(new java.awt.Color(255, 77, 77));
            jTable_HoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    jTable_HoaDonMouseClicked(evt);
                }
            });
            jScrollPane1.setViewportView(jTable_HoaDon);

            jTable_NhanVien.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
            jTable_NhanVien.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {

                },
                new String [] {
                    "Title 1", "Title 2", "Title 3", "Title 4"
                }
            ));
            jTable_NhanVien.setRowHeight(25);
            jTable_NhanVien.setRowMargin(2);
            jTable_NhanVien.setSelectionBackground(new java.awt.Color(255, 77, 77));
            jTable_NhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    jTable_NhanVienMouseClicked(evt);
                }
            });
            jScrollPane2.setViewportView(jTable_NhanVien);

            jTable_Ve.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
            jTable_Ve.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {

                },
                new String [] {
                    "Title 1", "Title 2", "Title 3", "Title 4"
                }
            ));
            jTable_Ve.setRowHeight(25);
            jTable_Ve.setRowMargin(2);
            jTable_Ve.setSelectionBackground(new java.awt.Color(255, 77, 77));
            jScrollPane3.setViewportView(jTable_Ve);

            jLabel1.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
            jLabel1.setForeground(new java.awt.Color(255, 255, 255));
            jLabel1.setText("Danh Sách Nhân Viên");

            jLabel2.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
            jLabel2.setForeground(new java.awt.Color(255, 255, 255));
            jLabel2.setText("Hóa Đơn Tương Ứng");

            jLabel3.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
            jLabel3.setForeground(new java.awt.Color(255, 255, 255));
            jLabel3.setText("SĐT nhân viên");

            jLabel4.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
            jLabel4.setForeground(new java.awt.Color(255, 255, 255));
            jLabel4.setText("Vé Trong Hóa Đơn Đã Chọn");

            jTextField_SDTNhanVien.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
            jTextField_SDTNhanVien.setEnabled(false);

            jLabel5.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
            jLabel5.setForeground(new java.awt.Color(255, 255, 255));
            jLabel5.setText("Tên nhân viên");

            jTextField_TenNhanVien.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

            jButton_QuayLai.setBackground(new java.awt.Color(0, 102, 102));
            jButton_QuayLai.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
            jButton_QuayLai.setForeground(new java.awt.Color(255, 255, 255));
            jButton_QuayLai.setText("Quay Lại");
            jButton_QuayLai.setBorderPainted(false);
            jButton_QuayLai.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton_QuayLaiActionPerformed(evt);
                }
            });

            jLabel9.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
            jLabel9.setForeground(new java.awt.Color(255, 255, 255));
            jLabel9.setText("Thông tin cơ bản của nhân viên");

            jTextField_TimKiem.addFocusListener(new java.awt.event.FocusAdapter() {
                public void focusGained(java.awt.event.FocusEvent evt) {
                    jTextField_TimKiemFocusGained(evt);
                }
                public void focusLost(java.awt.event.FocusEvent evt) {
                    jTextField_TimKiemFocusLost(evt);
                }
            });
            jTextField_TimKiem.addKeyListener(new java.awt.event.KeyAdapter() {
                public void keyReleased(java.awt.event.KeyEvent evt) {
                    jTextField_TimKiemKeyReleased(evt);
                }
            });

            jButton_ThemNhanVien.setBackground(new java.awt.Color(255, 121, 63));
            jButton_ThemNhanVien.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
            jButton_ThemNhanVien.setForeground(new java.awt.Color(255, 255, 255));
            jButton_ThemNhanVien.setText("Thêm Nhân Viên");
            jButton_ThemNhanVien.setBorderPainted(false);
            jButton_ThemNhanVien.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton_ThemNhanVienActionPerformed(evt);
                }
            });

            jButton_XoaNhanVien.setBackground(java.awt.Color.red);
            jButton_XoaNhanVien.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
            jButton_XoaNhanVien.setForeground(new java.awt.Color(255, 255, 255));
            jButton_XoaNhanVien.setText("Xóa Nhân Viên");
            jButton_XoaNhanVien.setBorderPainted(false);
            jButton_XoaNhanVien.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton_XoaNhanVienActionPerformed(evt);
                }
            });

            jLabel6.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
            jLabel6.setForeground(new java.awt.Color(255, 255, 255));
            jLabel6.setText("Địa chỉ");

            jLabel7.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
            jLabel7.setForeground(new java.awt.Color(255, 255, 255));
            jLabel7.setText("Tên đăng nhập");

            jLabel_CMND.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
            jLabel_CMND.setForeground(new java.awt.Color(255, 255, 255));
            jLabel_CMND.setText("CMND");

            jTextField_TenDangNhap.setEnabled(false);

            jTextField_CMND.addKeyListener(new java.awt.event.KeyAdapter() {
                public void keyReleased(java.awt.event.KeyEvent evt) {
                    jTextField_CMNDKeyReleased(evt);
                }
            });

            jButton_SuaNhanVien.setBackground(new java.awt.Color(60, 60, 153));
            jButton_SuaNhanVien.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
            jButton_SuaNhanVien.setForeground(new java.awt.Color(255, 255, 255));
            jButton_SuaNhanVien.setText("Sửa Nhân Viên");
            jButton_SuaNhanVien.setBorderPainted(false);
            jButton_SuaNhanVien.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton_SuaNhanVienActionPerformed(evt);
                }
            });

            jLabel_BaoLoi.setForeground(new java.awt.Color(255, 255, 51));

            jCheckBox_HoaDonDaThanhToan.setBackground(new java.awt.Color(89, 98, 117));
            jCheckBox_HoaDonDaThanhToan.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
            jCheckBox_HoaDonDaThanhToan.setForeground(new java.awt.Color(255, 255, 255));
            jCheckBox_HoaDonDaThanhToan.setText("Đã thanh toán");
            jCheckBox_HoaDonDaThanhToan.addItemListener(new java.awt.event.ItemListener() {
                public void itemStateChanged(java.awt.event.ItemEvent evt) {
                    jCheckBox_HoaDonDaThanhToanItemStateChanged(evt);
                }
            });

            jLabel10.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
            jLabel10.setForeground(new java.awt.Color(255, 255, 255));
            jLabel10.setText("| Tìm theo SĐT");

            jLabel_PhanQuyen.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
            jLabel_PhanQuyen.setForeground(new java.awt.Color(255, 255, 255));
            jLabel_PhanQuyen.setText("Phân quyền");

            jComboBox_PhanQuyen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NhanVien", "QuanLy" }));

            jButton_KhoiPhucMK.setBackground(new java.awt.Color(255, 77, 77));
            jButton_KhoiPhucMK.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
            jButton_KhoiPhucMK.setForeground(java.awt.Color.white);
            jButton_KhoiPhucMK.setText("Khôi phục MK");
            jButton_KhoiPhucMK.setBorderPainted(false);
            jButton_KhoiPhucMK.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton_KhoiPhucMKActionPerformed(evt);
                }
            });

            javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
            jPanel2.setLayout(jPanel2Layout);
            jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jSeparator1)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jScrollPane1))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(1, 1, 1)
                                    .addComponent(jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel10)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextField_TimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel9)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jButton_QuayLai, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton_KhoiPhucMK))
                                .addComponent(jLabel_BaoLoi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel7)
                                        .addComponent(jLabel_CMND)
                                        .addComponent(jLabel_PhanQuyen))
                                    .addGap(134, 134, 134)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTextField_TenNhanVien)
                                        .addComponent(jTextField_SDTNhanVien)
                                        .addComponent(jTextField_DiaChi)
                                        .addComponent(jTextField_TenDangNhap)
                                        .addComponent(jTextField_CMND)
                                        .addComponent(jComboBox_PhanQuyen, 0, 187, Short.MAX_VALUE))))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 833, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jCheckBox_HoaDonDaThanhToan))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addGap(1, 1, 1)
                                            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jLabel4)
                                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(jButton_ThemNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(42, 42, 42)
                                            .addComponent(jButton_XoaNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(39, 39, 39)
                                            .addComponent(jButton_SuaNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(0, 0, Short.MAX_VALUE)))))
                    .addContainerGap())
            );

            jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton_KhoiPhucMK, jButton_SuaNhanVien});

            jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2)
                        .addComponent(jTextField_TimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jCheckBox_HoaDonDaThanhToan)
                        .addComponent(jLabel10))
                    .addGap(3, 3, 3)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addGap(3, 3, 3)
                            .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                            .addComponent(jLabel_BaoLoi, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel9)
                                    .addGap(13, 13, 13)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(jTextField_SDTNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5)
                                .addComponent(jTextField_TenNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6)
                                .addComponent(jTextField_DiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7)
                                .addComponent(jTextField_TenDangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel_CMND)
                                .addComponent(jTextField_CMND, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel_PhanQuyen)
                                .addComponent(jComboBox_PhanQuyen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(0, 0, Short.MAX_VALUE)))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jButton_QuayLai, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton_XoaNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton_SuaNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_ThemNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton_KhoiPhucMK)))
                    .addGap(48, 48, 48))
            );

            jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButton_QuayLai, jButton_ThemNhanVien, jButton_XoaNhanVien});

            jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jTextField_CMND, jTextField_DiaChi, jTextField_TenDangNhap, jTextField_TenNhanVien});

            jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jTextField_SDTNhanVien, jTextField_TimKiem});

            jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButton_KhoiPhucMK, jButton_SuaNhanVien});

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );

            pack();
        }// </editor-fold>//GEN-END:initComponents

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel2MousePressed

    private void jCheckBox_HoaDonDaThanhToanItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBox_HoaDonDaThanhToanItemStateChanged
        // TODO add your handling code here:
        int row = jTable_NhanVien.getSelectedRow();
        if (row == -1) {
            dtmHoaDon.setRowCount(0);
            dtmVe.setRowCount(0);
        } else {
            this.sdtNhanVien = (String) jTable_NhanVien.getValueAt(row, 0);
            if (jCheckBox_HoaDonDaThanhToan.isSelected()) {
                loadBangHoaDonDaThanhToanTheoSDTNhanVien();
            } else {
                loadBangHoaDonTheoSDTNhanVien();
            }
        }
    }//GEN-LAST:event_jCheckBox_HoaDonDaThanhToanItemStateChanged

    private void jButton_SuaNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SuaNhanVienActionPerformed
        // TODO add your handling code here:
        int row = jTable_NhanVien.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(null, "Bạn vui lòng chọn nhân viên cần sửa");
        } else {
            NhanVien nv = new NhanVien(jTextField_SDTNhanVien.getText(), jTextField_TenNhanVien.getText(), jTextField_DiaChi.getText(),
                    jTextField_TenDangNhap.getText(), jTextField_CMND.getText());
            if (nv.getCmnd().isEmpty() || nv.getTenNhanVien().isEmpty() || nv.getDiaChi().isEmpty()) {
                jLabel_BaoLoi.setText("*Không bỏ trống thông tin");
            } else {
                jLabel_BaoLoi.setText("");
                int luaChon = JOptionPane.showConfirmDialog(rootPane, "", "Xác nhận sửa nhân viên", JOptionPane.OK_CANCEL_OPTION);
                if (luaChon == JOptionPane.OK_OPTION) {
                    if (connection.UpdateData.updateNhanVien(nv)) {
                        connection.UpdateData.updateTaiKhoan(sdtNhanVien, jComboBox_PhanQuyen.getSelectedItem().toString());
                        JOptionPane.showMessageDialog(rootPane, "Sửa nhân viên " + nv.getSdtNhanVien() + " thành công");
                        loadBangNhanVien();
                        clearTextFieldThongTinNhanVien();
                    } else {
                        JOptionPane.showMessageDialog(rootPane, "Sửa nhân viên " + nv.getSdtNhanVien() + " thất bại");
                    }
                }

            }
        }
    }//GEN-LAST:event_jButton_SuaNhanVienActionPerformed

    private void jTextField_CMNDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_CMNDKeyReleased
        // TODO add your handling code here:
        String cmnd = jTextField_CMND.getText();
        jLabel_BaoLoi.setText("");
        jLabel_CMND.setForeground(Color.white);
        jTextField_CMND.setForeground(Color.black);
        for (int i = 0; i < cmnd.length(); i++) {
            if (cmnd.charAt(i) < '0' || cmnd.charAt(i) > '9') {
                jLabel_BaoLoi.setText("*CMND phải nhập số");
                jLabel_CMND.setForeground(Color.yellow);
                jTextField_CMND.setForeground(Color.yellow);
                break;
            }
        }
    }//GEN-LAST:event_jTextField_CMNDKeyReleased

    private void jButton_XoaNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_XoaNhanVienActionPerformed
        // TODO add your handling code here:
        int row = jTable_NhanVien.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(null, "Bạn vui lòng chọn nhân viên cần xóa");
        } else {
            this.sdtNhanVien = (String) jTable_NhanVien.getValueAt(row, 0);
            int luaChon = JOptionPane.showConfirmDialog(rootPane, "", "Xác nhận xóa nhân viên", JOptionPane.OK_CANCEL_OPTION);
            if (luaChon == JOptionPane.OK_OPTION) {
                if (connection.UpdateData.deleteNhanVien(this.sdtNhanVien)) {
                    connection.UpdateData.deleteTaiKhoan(this.sdtNhanVien);
                    JOptionPane.showMessageDialog(rootPane, "Xóa nhân viên " + this.sdtNhanVien + " thành công");
                    loadBangNhanVien();
                    clearTextFieldThongTinNhanVien();
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Xóa nhân viên " + this.sdtNhanVien + " thất bại");
                }
            }
        }
    }//GEN-LAST:event_jButton_XoaNhanVienActionPerformed

    private void jButton_ThemNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ThemNhanVienActionPerformed
        // TODO add your handling code here:
        new GiaoDienThemNhanVien().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton_ThemNhanVienActionPerformed

    private void jTextField_TimKiemKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_TimKiemKeyReleased
        // TODO add your handling code here:
        clearTextFieldThongTinNhanVien();

        if (jTextField_TimKiem.getText().length() >= 11) {
            jTextField_TimKiem.setText(jTextField_TimKiem.getText().substring(0, jTextField_TimKiem.getText().length() - 1));
        } else {
            dtmNhanVien.setRowCount(0);
            new LoadData();
            int length = jTextField_TimKiem.getText().length();
            for (NhanVien nv : controller.Controller.arrayListNhanVien) {
                if ((jTextField_TimKiem.getText()).equalsIgnoreCase(nv.getSdtNhanVien().substring(0, length))) {
                    dtmNhanVien.addRow(new Object[]{
                        nv.getSdtNhanVien(), nv.getTenNhanVien()
                    });
                }
            }
            if (jTextField_TimKiem.getText().isEmpty()) {
                loadBangNhanVien();
            }
        }
    }//GEN-LAST:event_jTextField_TimKiemKeyReleased

    private void jTextField_TimKiemFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_TimKiemFocusLost
        // TODO add your handling code here:
        if (jTextField_TimKiem.getText().isEmpty()) {
            jTextField_TimKiem.setText("Tìm nhân viên theo sđt");
            jTextField_TimKiem.setForeground(Color.gray);
        }
    }//GEN-LAST:event_jTextField_TimKiemFocusLost

    private void jTextField_TimKiemFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_TimKiemFocusGained
        // TODO add your handling code here:
        if (jTextField_TimKiem.getText().equals("Tìm nhân viên theo sđt")) {
            jTextField_TimKiem.setText("");
            jTextField_TimKiem.setForeground(Color.black);
        }
    }//GEN-LAST:event_jTextField_TimKiemFocusGained

    private void jButton_QuayLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_QuayLaiActionPerformed
        // TODO add your handling code here:
        this.dispose();

        new GiaoDienQuanLy().setVisible(true);
    }//GEN-LAST:event_jButton_QuayLaiActionPerformed

    private void jTable_NhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_NhanVienMouseClicked
        // TODO add your handling code here:
        int row = jTable_NhanVien.getSelectedRow();
        if (row == -1) {

        } else {
            this.sdtNhanVien = (String) jTable_NhanVien.getValueAt(row, 0);
            System.out.println("SDT của nhân viên đã chọn: " + this.sdtNhanVien);
            if (jCheckBox_HoaDonDaThanhToan.isSelected()) {
                loadBangHoaDonDaThanhToanTheoSDTNhanVien();
            } else {
                loadBangHoaDonTheoSDTNhanVien();
            }
        }
    }//GEN-LAST:event_jTable_NhanVienMouseClicked

    private void jTable_HoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_HoaDonMouseClicked
        // TODO add your handling code here:
        int row = jTable_HoaDon.getSelectedRow();
        if (row == -1) {
        } else {
            String maHoaDon = (String) jTable_HoaDon.getValueAt(row, 0);
            new LoadData();
            dtmVe.setRowCount(0);
            for (Ve v : controller.Controller.arrayListVe) {
                if (v.getMaHoaDon().equals(maHoaDon)) {
                    if (v.getNgaySinh() != null) {
                        dtmVe.addRow(new Object[]{
                            v.getMaVe(), v.getMaChuyenBay(), v.getGia(), v.getKyGui(),
                            v.getCmndNguoiBay(), v.getTenNguoiBay(), new SimpleDateFormat("dd/MM/yyyy").format(v.getNgaySinh()),
                            v.getMaHoaDon(), v.getMaGhe()
                        });
                    } else {
                        dtmVe.addRow(new Object[]{
                            v.getMaVe(), v.getMaChuyenBay(), v.getGia(), v.getKyGui(),
                            v.getCmndNguoiBay(), v.getTenNguoiBay(), "",
                            v.getMaHoaDon(), v.getMaGhe()
                        });
                    }
                }
            }
        }
    }//GEN-LAST:event_jTable_HoaDonMouseClicked

    private void jButton_KhoiPhucMKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_KhoiPhucMKActionPerformed
        if (jTable_NhanVien.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(null, "Bạn vui chọn nhân viên cần khôi phục mật khẩu");
            return;
        }
        int confirm = JOptionPane.showConfirmDialog(null,
                "Mật khẩu sẽ được khôi phục thành 123. Bạn có chắc chắn muốn khôi phục?");
        if (confirm == JOptionPane.YES_OPTION) {
            TaiKhoan taiKhoan = null;
            int vt = 0;
            for (TaiKhoan tk : Controller.arrayListTaiKhoan) {
                if (tk.getSdt().equals(sdtNhanVien)) {
                    taiKhoan = tk;
                    break;
                }
                vt++;
            }
            taiKhoan.setMatKhau("123");
            Controller.arrayListTaiKhoan.set(vt, taiKhoan);
            UpdateData.updateTaiKhoan(taiKhoan);
            JOptionPane.showMessageDialog(null, "Mật khẩu đã được khôi phục");
        }
    }//GEN-LAST:event_jButton_KhoiPhucMKActionPerformed

    private void loadBangHoaDonDaThanhToanTheoSDTNhanVien() {
        new LoadData();
        dtmHoaDon.setRowCount(0);

        for (NhanVien nv : controller.Controller.arrayListNhanVien) {
            if (nv.getSdtNhanVien().equals(this.sdtNhanVien)) {
                jTextField_SDTNhanVien.setText(nv.getSdtNhanVien());
                jTextField_TenNhanVien.setText(nv.getTenNhanVien());
                jTextField_DiaChi.setText(nv.getDiaChi());
                jTextField_CMND.setText(nv.getCmnd());
                jTextField_TenDangNhap.setText(nv.getTenDangNhap());
            }
        }
        for (TaiKhoan tk : controller.Controller.arrayListTaiKhoan) {
            if (tk.getSdt().trim().equals(this.sdtNhanVien.trim())) {
                jComboBox_PhanQuyen.setSelectedItem(tk.getLoaiTaiKhoan());
                break;
            }
        }
        for (HoaDon hd : controller.Controller.arrayListHoaDon) {
            if (hd.getSdtNhanVien().equals(this.sdtNhanVien)) {
                if (hd.getTrangThaiThanhToan() == 1) {
                    dtmHoaDon.addRow(new Object[]{
                        hd.getMaHoaDon(), hd.getSdtKhachHang(), new SimpleDateFormat("dd/MM/yyyy").format(hd.getNgayXuatHoaDon()),
                        hd.getTrangThaiThanhToan(), hd.getTongTien(), hd.getSdtNhanVien()
                    });
                }
            }
        }
    }

    private void loadBangHoaDonTheoSDTNhanVien() {
        new LoadData();
        dtmHoaDon.setRowCount(0);
        for (HoaDon hd : controller.Controller.arrayListHoaDon) {
            if (hd.getSdtNhanVien().equals(this.sdtNhanVien)) {
                dtmHoaDon.addRow(new Object[]{
                    hd.getMaHoaDon(), hd.getSdtKhachHang(), new SimpleDateFormat("dd/MM/yyyy").format(hd.getNgayXuatHoaDon()),
                    hd.getTrangThaiThanhToan(), hd.getTongTien(), hd.getSdtNhanVien()
                });
            }
        }
        for (NhanVien nv : controller.Controller.arrayListNhanVien) {
            if (nv.getSdtNhanVien().equals(this.sdtNhanVien)) {
                jTextField_SDTNhanVien.setText(nv.getSdtNhanVien());
                jTextField_TenNhanVien.setText(nv.getTenNhanVien());
                jTextField_DiaChi.setText(nv.getDiaChi());
                jTextField_CMND.setText(nv.getCmnd());
                jTextField_TenDangNhap.setText(nv.getTenDangNhap());
            }
        }
        for (TaiKhoan tk : controller.Controller.arrayListTaiKhoan) {
            if (tk.getSdt().trim().equals(this.sdtNhanVien.trim())) {
                jComboBox_PhanQuyen.setSelectedItem(tk.getLoaiTaiKhoan());
                break;
            }
        }
    }

    private void clearTextFieldThongTinNhanVien() {
        jTextField_CMND.setText("");
        jTextField_SDTNhanVien.setText("");
        jTextField_TenNhanVien.setText("");
        jTextField_DiaChi.setText("");
        jTextField_TenDangNhap.setText("");
    }

    private void loadBangNhanVien() {
        dtmNhanVien.setRowCount(0);
        new LoadData();
        for (NhanVien nv : controller.Controller.arrayListNhanVien) {
            for (TaiKhoan tk : controller.Controller.arrayListTaiKhoan) {
                if (nv.getSdtNhanVien().equals(tk.getSdt())) {
                    if (tk.getLoaiTaiKhoan().equalsIgnoreCase("NhanVien") || tk.getLoaiTaiKhoan().equalsIgnoreCase("QuanLy")) {
                        dtmNhanVien.addRow(new Object[]{
                            nv.getSdtNhanVien(), nv.getTenNhanVien()
                        });
                    }
                }
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GiaoDienQuanLyNhanVien.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GiaoDienQuanLyNhanVien.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GiaoDienQuanLyNhanVien.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GiaoDienQuanLyNhanVien.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GiaoDienQuanLyNhanVien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_KhoiPhucMK;
    private javax.swing.JButton jButton_QuayLai;
    private javax.swing.JButton jButton_SuaNhanVien;
    private javax.swing.JButton jButton_ThemNhanVien;
    private javax.swing.JButton jButton_XoaNhanVien;
    private javax.swing.JCheckBox jCheckBox_HoaDonDaThanhToan;
    private javax.swing.JComboBox<String> jComboBox_PhanQuyen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_AirLines;
    private javax.swing.JLabel jLabel_BaoLoi;
    private javax.swing.JLabel jLabel_CMND;
    private javax.swing.JLabel jLabel_HPT;
    private javax.swing.JLabel jLabel_IconMayBay;
    private javax.swing.JLabel jLabel_PhanQuyen;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTable jTable_HoaDon;
    private javax.swing.JTable jTable_NhanVien;
    private javax.swing.JTable jTable_Ve;
    private javax.swing.JTextField jTextField_CMND;
    private javax.swing.JTextField jTextField_DiaChi;
    private javax.swing.JTextField jTextField_SDTNhanVien;
    private javax.swing.JTextField jTextField_TenDangNhap;
    private javax.swing.JTextField jTextField_TenNhanVien;
    private javax.swing.JTextField jTextField_TimKiem;
    // End of variables declaration//GEN-END:variables
}
