package view;

import connection.LoadData;
import controller.Controller;
import java.awt.Color;
import java.awt.Component;
import java.awt.Cursor;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import static javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE;
import model.ChuyenBay;
import model.Ghe;
import model.KhachHang;
import model.NhanVien;

/**
 *
 * @author tuanbuiquoc
 */
public class GiaoDienTimChuyenBay extends javax.swing.JFrame {

    /**
     * Creates new form GiaoDienTimChuyenBay
     */
    public Date ngayHienTai;

    public GiaoDienTimChuyenBay() {
        initComponents();
        setVisible(true);

        String date = new SimpleDateFormat("dd/MM/yyyy").format(Calendar.getInstance().getTime());
        try {
            ngayHienTai = new SimpleDateFormat("dd/MM/yyyy").parse(date);
        } catch (ParseException ex) {
            Logger.getLogger(GiaoDienTimChuyenBay.class.getName()).log(Level.SEVERE, null, ex);
        }
        //
        if (!controller.Controller.tk.getLoaiTaiKhoan().equals("KhachHang")) {
            for (Component c : jPanel_TaiKhoan.getComponents()) {
                c.setForeground(new Color(48, 57, 82));
            }
        } else {
            jLabel_XemThongTinTaiKhoan.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
            jLabel_DangXuat.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        }
        thongTinTaiKhoan();
        inputMacDinh();

        if (controller.Controller.tk.getLoaiTaiKhoan().equals("KhachHang")) {
            jLabel_QuayLai.setVisible(false);
        }

        jLabel_HuongDanDatCho.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        jButton_TimChuyenBay.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        jLabel_QuayLai.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        this.addWindowListener(new WindowAdapter() {
            public void windowClosing(WindowEvent e) {
                int confirmed = JOptionPane.showConfirmDialog(null,
                        "Bạn có chắc muốn thoát chương trình không?", "Xác nhận",
                        JOptionPane.YES_NO_OPTION);
                if (confirmed == JOptionPane.YES_OPTION) {
                    dispose();
                } else {
                    setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
                }
            }
        });
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void thongTinTaiKhoan() {
        //// Phần thông tin cơ bản , đăng xuất

        new LoadData();
        for (NhanVien nv : controller.Controller.arrayListNhanVien) {
            if (nv.getSdtNhanVien().equals(controller.Controller.tk.getSdt())
                    && (controller.Controller.tk.getLoaiTaiKhoan().equals("NhanVien"))) {
                jLabel_PhanQuyen.setText("nhân viên");

                jLabel_TenNguoiDung.setText(nv.getTenNhanVien());
            }
            if (nv.getSdtNhanVien().equals(controller.Controller.tk.getSdt())
                    && (controller.Controller.tk.getLoaiTaiKhoan().equals("QuanLy"))) {
                jLabel_PhanQuyen.setText("quản lý");

                jLabel_TenNguoiDung.setText(nv.getTenNhanVien());
            }
        }
        for (KhachHang kh : controller.Controller.arrayListKhachHang) {
            if (kh.getSdtKhachHang().equals(controller.Controller.tk.getSdt())) {
                jLabel_PhanQuyen.setText("khách hàng");
                jLabel_TenNguoiDung.setText(kh.getTenKhachHang());
            }
        }
        ////
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel_IconMayBay = new javax.swing.JLabel();
        jLabel_HPT = new javax.swing.JLabel();
        jLabel_AirLines = new javax.swing.JLabel();
        jPanel_TaiKhoan = new javax.swing.JPanel();
        jLabel_XinChao = new javax.swing.JLabel();
        jLabel_PhanQuyen = new javax.swing.JLabel();
        jLabel_TenNguoiDung = new javax.swing.JLabel();
        jLabel_XemThongTinTaiKhoan = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel_DangXuat = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jRadioButton_MotChieu = new javax.swing.JRadioButton();
        jRadioButton_KhuHoi = new javax.swing.JRadioButton();
        jComboBox_SanBayDi = new javax.swing.JComboBox<>();
        jComboBox_SanBayDen = new javax.swing.JComboBox<>();
        jLabel_SanBayDi = new javax.swing.JLabel();
        jLabel_SanBayDen = new javax.swing.JLabel();
        jLabel_NgayDi = new javax.swing.JLabel();
        jLabel_NgayVe = new javax.swing.JLabel();
        jLabel_IconNgayDi = new javax.swing.JLabel();
        jLabel_IconNgayVe = new javax.swing.JLabel();
        jButton_TimChuyenBay = new javax.swing.JButton();
        jLabel_HuongDanDatCho = new javax.swing.JLabel();
        jLabel_NguoiLon = new javax.swing.JLabel();
        jLabel_TreEm = new javax.swing.JLabel();
        jComboBox_SLNguoiLon = new javax.swing.JComboBox<>();
        jComboBox_SLTreEm = new javax.swing.JComboBox<>();
        jDateChooser_NgayDi = new com.toedter.calendar.JDateChooser();
        jDateChooser_NgayVe = new com.toedter.calendar.JDateChooser();
        jLabel_BaoLoi = new javax.swing.JLabel();
        jLabel_QuayLai = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tìm chuyến bay");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(48, 57, 82));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        jLabel_IconMayBay.setForeground(new java.awt.Color(204, 255, 255));
        jLabel_IconMayBay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/images/icons8_airplane_48px_4.png"))); // NOI18N

        jLabel_HPT.setFont(new java.awt.Font("Roboto Mono Light", 1, 48)); // NOI18N
        jLabel_HPT.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_HPT.setText("HPT");

        jLabel_AirLines.setFont(new java.awt.Font("Roboto Light", 1, 24)); // NOI18N
        jLabel_AirLines.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_AirLines.setText("AIRLINES™");

        jPanel_TaiKhoan.setBackground(new java.awt.Color(48, 57, 82));

        jLabel_XinChao.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel_XinChao.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_XinChao.setText("Xin chào,");

        jLabel_PhanQuyen.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel_PhanQuyen.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_PhanQuyen.setText("Đối tượng");

        jLabel_TenNguoiDung.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel_TenNguoiDung.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_TenNguoiDung.setText("Tên đối tượng");

        jLabel_XemThongTinTaiKhoan.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel_XemThongTinTaiKhoan.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_XemThongTinTaiKhoan.setText("<HTML><u>Xem thông tin tài khoản</u></HTML>");
        jLabel_XemThongTinTaiKhoan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel_XemThongTinTaiKhoanMousePressed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("|");

        jLabel_DangXuat.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel_DangXuat.setForeground(new java.awt.Color(255, 77, 77));
        jLabel_DangXuat.setText("<HTML><u>Đăng xuất</u></HTML>");
        jLabel_DangXuat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel_DangXuatMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_TaiKhoanLayout = new javax.swing.GroupLayout(jPanel_TaiKhoan);
        jPanel_TaiKhoan.setLayout(jPanel_TaiKhoanLayout);
        jPanel_TaiKhoanLayout.setHorizontalGroup(
            jPanel_TaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_TaiKhoanLayout.createSequentialGroup()
                .addGroup(jPanel_TaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_TaiKhoanLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jLabel_XemThongTinTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jLabel_DangXuat, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel_TaiKhoanLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel_XinChao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_PhanQuyen, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_TenNguoiDung, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel_TaiKhoanLayout.setVerticalGroup(
            jPanel_TaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_TaiKhoanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_TaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_TenNguoiDung, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel_TaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel_XinChao)
                        .addComponent(jLabel_PhanQuyen)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_TaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_XemThongTinTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel_DangXuat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel_IconMayBay)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel_HPT)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_AirLines, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel_TaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel_TaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_HPT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel_AirLines, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel_IconMayBay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(89, 98, 117));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });

        jRadioButton_MotChieu.setBackground(new java.awt.Color(89, 98, 117));
        buttonGroup1.add(jRadioButton_MotChieu);
        jRadioButton_MotChieu.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        jRadioButton_MotChieu.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton_MotChieu.setText("Một chiều");
        jRadioButton_MotChieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_MotChieuActionPerformed(evt);
            }
        });

        jRadioButton_KhuHoi.setBackground(new java.awt.Color(89, 98, 117));
        buttonGroup1.add(jRadioButton_KhuHoi);
        jRadioButton_KhuHoi.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        jRadioButton_KhuHoi.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton_KhuHoi.setText("Khứ hồi");
        jRadioButton_KhuHoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_KhuHoiActionPerformed(evt);
            }
        });

        jComboBox_SanBayDi.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N

        jComboBox_SanBayDen.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jComboBox_SanBayDen.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox_SanBayDenItemStateChanged(evt);
            }
        });

        jLabel_SanBayDi.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        jLabel_SanBayDi.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_SanBayDi.setText("Sân bay đi");

        jLabel_SanBayDen.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        jLabel_SanBayDen.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_SanBayDen.setText("Sân bay đến");

        jLabel_NgayDi.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        jLabel_NgayDi.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_NgayDi.setText("Ngày đi");

        jLabel_NgayVe.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        jLabel_NgayVe.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_NgayVe.setText("Ngày về");

        jLabel_IconNgayDi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/images/icons8_airplane_take_off_30px.png"))); // NOI18N

        jLabel_IconNgayVe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/images/icons8_airplane_landing_26px_1.png"))); // NOI18N
        jLabel_IconNgayVe.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);

        jButton_TimChuyenBay.setBackground(new java.awt.Color(255, 77, 77));
        jButton_TimChuyenBay.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jButton_TimChuyenBay.setForeground(new java.awt.Color(255, 255, 255));
        jButton_TimChuyenBay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/images/icons8_search_32px_1.png"))); // NOI18N
        jButton_TimChuyenBay.setText("TÌM CHUYẾN BAY");
        jButton_TimChuyenBay.setBorderPainted(false);
        jButton_TimChuyenBay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_TimChuyenBayActionPerformed(evt);
            }
        });

        jLabel_HuongDanDatCho.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel_HuongDanDatCho.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_HuongDanDatCho.setText("<HTML>*<U>Hướng dẫn đặt chỗ</U></HTML>");
        jLabel_HuongDanDatCho.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel_HuongDanDatChoMousePressed(evt);
            }
        });

        jLabel_NguoiLon.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel_NguoiLon.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_NguoiLon.setText("Người lớn (>=16t)");

        jLabel_TreEm.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel_TreEm.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_TreEm.setText("Trẻ em (2-15t)");

        jComboBox_SLNguoiLon.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jComboBox_SLNguoiLon.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        jComboBox_SLTreEm.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jComboBox_SLTreEm.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        jDateChooser_NgayDi.setDateFormatString("dd/MM/yyyy");
        jDateChooser_NgayDi.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jDateChooser_NgayDi.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jDateChooser_NgayDiPropertyChange(evt);
            }
        });

        jDateChooser_NgayVe.setDateFormatString("dd/MM/yyyy");
        jDateChooser_NgayVe.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N

        jLabel_BaoLoi.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        jLabel_BaoLoi.setForeground(java.awt.Color.yellow);

        jLabel_QuayLai.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel_QuayLai.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_QuayLai.setText("Quay Lại");
        jLabel_QuayLai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel_QuayLaiMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel_SanBayDi)
                                    .addComponent(jLabel_SanBayDen)
                                    .addComponent(jComboBox_SanBayDi, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jComboBox_SanBayDen, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jLabel_NgayDi, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(40, 40, 40)
                                                .addComponent(jLabel_IconNgayDi))
                                            .addComponent(jDateChooser_NgayDi, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jLabel_NgayVe, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(40, 40, 40)
                                                .addComponent(jLabel_IconNgayVe))
                                            .addComponent(jDateChooser_NgayVe, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel_NguoiLon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel_TreEm, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jComboBox_SLTreEm, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jComboBox_SLNguoiLon, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jRadioButton_MotChieu)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton_KhuHoi, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel_HuongDanDatCho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(80, 80, 80)
                                .addComponent(jLabel_BaoLoi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel_QuayLai))
                    .addComponent(jButton_TimChuyenBay, javax.swing.GroupLayout.PREFERRED_SIZE, 583, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton_MotChieu)
                    .addComponent(jRadioButton_KhuHoi))
                .addGap(11, 11, 11)
                .addComponent(jLabel_SanBayDi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox_SanBayDi)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel_NguoiLon)
                        .addComponent(jComboBox_SLNguoiLon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(13, 13, 13)
                .addComponent(jLabel_SanBayDen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox_SanBayDen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel_TreEm)
                        .addComponent(jComboBox_SLTreEm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel_NgayVe)
                    .addComponent(jLabel_NgayDi)
                    .addComponent(jLabel_IconNgayVe, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_IconNgayDi, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jDateChooser_NgayVe, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(jDateChooser_NgayDi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(36, 36, 36)
                .addComponent(jButton_TimChuyenBay, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_BaoLoi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_HuongDanDatCho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_QuayLai))
                        .addGap(0, 24, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jComboBox_SanBayDen, jComboBox_SanBayDi});

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel_IconNgayDi, jLabel_IconNgayVe});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void inputMacDinh() {
        controller.Controller.arrayListSanBay.removeAll(controller.Controller.arrayListSanBay);
        new LoadData();
        for (model.SanBay sb : controller.Controller.arrayListSanBay) {
            jComboBox_SanBayDi.addItem(sb.getMaSanBay().trim() + "-" + sb.getTenSanBay());
            jComboBox_SanBayDen.addItem(sb.getMaSanBay().trim() + "-" + sb.getTenSanBay());
        }

        jDateChooser_NgayDi.setDate(ngayHienTai);
        jDateChooser_NgayVe.setDate(ngayHienTai);

        jComboBox_SanBayDen.setSelectedIndex(1);
        jRadioButton_MotChieu.setSelected(true);
        jDateChooser_NgayVe.setEnabled(false);
    }

    private boolean baoLoiInput() {

        boolean ktra = true;

        if (Integer.parseInt(jComboBox_SLNguoiLon.getSelectedItem().toString()) == 0) {
            jComboBox_SLNguoiLon.setBorder(BorderFactory.createLineBorder(Color.yellow, 1));
            jLabel_BaoLoi.setText("Trẻ em cần có người lớn đi cùng.");
            ktra = false;
            return ktra;
        } else {
            jComboBox_SLNguoiLon.setBorder(BorderFactory.createLineBorder(Color.gray, 1));
            jLabel_BaoLoi.setText("");
            ktra = true;
        }

        if (jComboBox_SanBayDi.getSelectedItem().toString().equalsIgnoreCase(jComboBox_SanBayDen.getSelectedItem().toString())) {
            jComboBox_SanBayDen.setBorder(BorderFactory.createLineBorder(Color.yellow, 1));
            jComboBox_SanBayDi.setBorder(BorderFactory.createLineBorder(Color.yellow, 1));
            jLabel_BaoLoi.setText("Sân bay đi và sân bay đến không thể trùng nhau.");
            ktra = false;
            return ktra;
        } else {
            jComboBox_SanBayDi.setBorder(BorderFactory.createLineBorder(Color.gray, 1));
            jComboBox_SanBayDen.setBorder(BorderFactory.createLineBorder(Color.gray, 1));
            jLabel_BaoLoi.setText("");
        }

        Date ngayDi = jDateChooser_NgayDi.getDate();
        Date ngayVe = jDateChooser_NgayVe.getDate();

        if ((ngayHienTai.after(ngayDi))) {
            jDateChooser_NgayDi.setBorder(BorderFactory.createLineBorder(Color.yellow, 1));
            ktra = false;
            jLabel_BaoLoi.setText("Ngày đi không hợp lệ.");
            return ktra;
        } else {
            jDateChooser_NgayDi.setBorder(BorderFactory.createLineBorder(Color.gray, 1));
            jLabel_BaoLoi.setText("");
        }

        if (jRadioButton_KhuHoi.isSelected()) {
            if ((ngayHienTai.after(ngayVe))) {
                jDateChooser_NgayVe.setBorder(BorderFactory.createLineBorder(Color.yellow, 1));
                ktra = false;
                jLabel_BaoLoi.setText("Ngày về phải trước ngày hiện tại.");
                return ktra;
            } else {
                jLabel_BaoLoi.setText("");
                jDateChooser_NgayVe.setBorder(BorderFactory.createLineBorder(Color.gray, 1));
            }
            if (ngayDi.after(ngayVe)) {
                jDateChooser_NgayDi.setBorder(BorderFactory.createLineBorder(Color.yellow, 1));
                jLabel_BaoLoi.setText("Ngày đi phải trước ngày về.");
                jDateChooser_NgayVe.setBorder(BorderFactory.createLineBorder(Color.yellow, 1));
                ktra = false;
                return ktra;
            } else {
                jDateChooser_NgayDi.setBorder(BorderFactory.createLineBorder(Color.gray, 1));
                jLabel_BaoLoi.setText("");
                jDateChooser_NgayVe.setBorder(BorderFactory.createLineBorder(Color.gray, 1));
                ktra = true;
            }
        }

        return ktra;
    }
    private void jRadioButton_KhuHoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_KhuHoiActionPerformed
        // TODO add your handling code here:
        jDateChooser_NgayVe.setEnabled(true);
    }//GEN-LAST:event_jRadioButton_KhuHoiActionPerformed

    private void jButton_TimChuyenBayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_TimChuyenBayActionPerformed
        // TODO add your handling code here:
        if (baoLoiInput() == true) {
            String maSanBayDi = jComboBox_SanBayDi.getSelectedItem().toString().substring(0, 3);
            String maSanBayDen = jComboBox_SanBayDen.getSelectedItem().toString().substring(0, 3);
            Date ngayDi = jDateChooser_NgayDi.getDate();
            Date ngayVe = null;
            boolean khuHoi = false;
            boolean di = true;
            boolean ve = false;
            int soGheNguoiLon = Integer.parseInt(jComboBox_SLNguoiLon.getSelectedItem().toString());
            int soGheTreEm = Integer.parseInt(jComboBox_SLTreEm.getSelectedItem().toString());
            controller.Controller.arrayListKetQuaTimKiemChuyenBay.removeAll(controller.Controller.arrayListKetQuaTimKiemChuyenBay);
            Controller.loadKetQuaTheoNgay(jComboBox_SanBayDi.getSelectedItem().toString().substring(0, 3),
                    jComboBox_SanBayDen.getSelectedItem().toString().substring(0, 3), new SimpleDateFormat("yyyy-MM-dd").format(ngayDi));
            if (!controller.Controller.arrayListKetQuaTimKiemChuyenBay.isEmpty()) {
                for (ChuyenBay cb : controller.Controller.arrayListKetQuaTimKiemChuyenBay) {
                    int soGheTrong = 0;
                    for (Ghe g : cb.getArrayListGhe()) {
                        if (g.getTrong() == 1) {
                            soGheTrong++;
                        }
                    }
                    if (soGheTrong >= (soGheNguoiLon + soGheTreEm)) {
                        break;
                    } else {
                        JOptionPane.showMessageDialog(rootPane, "Không có chuyến đi đủ ghế");
                        return;
                    }
                }
            } else {
                JOptionPane.showMessageDialog(rootPane, "Không có chuyến đi");
                return;
            }
            if (jRadioButton_KhuHoi.isSelected()) {
                ve = true;
                khuHoi = true;
                ngayVe = jDateChooser_NgayVe.getDate();

                controller.Controller.arrayListKetQuaTimKiemChuyenBay.removeAll(controller.Controller.arrayListKetQuaTimKiemChuyenBay);
                Controller.loadKetQuaTheoNgay(jComboBox_SanBayDen.getSelectedItem().toString().substring(0, 3),
                        jComboBox_SanBayDi.getSelectedItem().toString().substring(0, 3), new SimpleDateFormat("yyyy-MM-dd").format(ngayVe));
                if (!controller.Controller.arrayListKetQuaTimKiemChuyenBay.isEmpty()) {
                    for (ChuyenBay cb : controller.Controller.arrayListKetQuaTimKiemChuyenBay) {
                        int soGheTrong = 0;
                        for (Ghe g : cb.getArrayListGhe()) {
                            if (g.getTrong() == 1) {
                                soGheTrong++;
                            }
                        }
                        if (soGheTrong >= (soGheNguoiLon + soGheTreEm)) {
                            break;
                        } else {
                            JOptionPane.showMessageDialog(rootPane, "Không có chuyến về đủ ghế");
                            return;
                        }
                    }
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Không có chuyến về");
                    return;
                }
            }

            new GiaoDienChonChuyenBayDi(maSanBayDi, maSanBayDen, ngayDi, ngayVe, di, ve, khuHoi, soGheNguoiLon, soGheTreEm).setVisible(true);
            this.dispose();
        }
        if (baoLoiInput() == false) {
            JOptionPane.showMessageDialog(rootPane, "Không thể tìm chuyến bay");
        }

    }//GEN-LAST:event_jButton_TimChuyenBayActionPerformed

    private void jRadioButton_MotChieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_MotChieuActionPerformed
        // TODO add your handling code here:
        jDateChooser_NgayVe.setEnabled(false);
    }//GEN-LAST:event_jRadioButton_MotChieuActionPerformed

    private void jLabel_HuongDanDatChoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_HuongDanDatChoMousePressed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(rootPane, "1. Sân bay đi và đến không được trùng nhau.\n"
                + "2. Phải có ít nhất một người lớn.\n"
                + "3. Vui lòng không chọn ngày trước ngày hiện tại.\n"
                + "");
    }//GEN-LAST:event_jLabel_HuongDanDatChoMousePressed

    private void jComboBox_SanBayDenItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox_SanBayDenItemStateChanged
        if (jComboBox_SanBayDi.getSelectedItem().toString().equalsIgnoreCase(jComboBox_SanBayDen.getSelectedItem().toString())) {
            jComboBox_SanBayDen.setBorder(BorderFactory.createLineBorder(Color.yellow, 1));
            jComboBox_SanBayDi.setBorder(BorderFactory.createLineBorder(Color.yellow, 1));
            jLabel_BaoLoi.setText("Sân bay đi và sân bay đến không thể trùng nhau.");
        } else {
            jComboBox_SanBayDi.setBorder(BorderFactory.createLineBorder(Color.gray, 1));
            jComboBox_SanBayDen.setBorder(BorderFactory.createLineBorder(Color.gray, 1));
            jLabel_BaoLoi.setText("");
        }
    }//GEN-LAST:event_jComboBox_SanBayDenItemStateChanged

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        // TODO add your handling code here:
        baoLoiInput();

    }//GEN-LAST:event_jPanel2MousePressed

    private void jDateChooser_NgayDiPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jDateChooser_NgayDiPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jDateChooser_NgayDiPropertyChange

    private void jLabel_XemThongTinTaiKhoanMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_XemThongTinTaiKhoanMousePressed
        // TODO add your handling code here:
        if (!controller.Controller.tk.getLoaiTaiKhoan().equals("KhachHang")) {
            return;
        }
        if (jLabel_PhanQuyen.getText().equals("nhân viên")) {
            this.dispose();
            new GiaoDienThongTinNhanVien().setVisible(true);
        }
        if (jLabel_PhanQuyen.getText().equals("quản lý")) {
            this.dispose();
            new GiaoDienThongTinNhanVien().setVisible(true);
        }
        if (jLabel_PhanQuyen.getText().equals("khách hàng")) {
            this.dispose();
            new GiaoDienThongTinKhachHang().setVisible(true);
        }
    }//GEN-LAST:event_jLabel_XemThongTinTaiKhoanMousePressed

    private void jLabel_DangXuatMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_DangXuatMousePressed
        // TODO add your handling code here:
        if (!controller.Controller.tk.getLoaiTaiKhoan().equals("KhachHang")) {
            return;
        }
        dispose();
        new GiaoDienDangNhap().setVisible(true);
    }//GEN-LAST:event_jLabel_DangXuatMousePressed

    private void jLabel_QuayLaiMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_QuayLaiMousePressed
        // TODO add your handling code here:
        if (Controller.tk.getLoaiTaiKhoan().equals("NhanVien")) {
            dispose();
            new GiaoDienNhanVien().setVisible(true);
        }
        if (Controller.tk.getLoaiTaiKhoan().equals("QuanLy")) {
            dispose();
            new GiaoDienQuanLy().setVisible(true);
        }
    }//GEN-LAST:event_jLabel_QuayLaiMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GiaoDienTimChuyenBay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GiaoDienTimChuyenBay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GiaoDienTimChuyenBay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GiaoDienTimChuyenBay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GiaoDienTimChuyenBay().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton_TimChuyenBay;
    private javax.swing.JComboBox<String> jComboBox_SLNguoiLon;
    private javax.swing.JComboBox<String> jComboBox_SLTreEm;
    private javax.swing.JComboBox<String> jComboBox_SanBayDen;
    private javax.swing.JComboBox<String> jComboBox_SanBayDi;
    private com.toedter.calendar.JDateChooser jDateChooser_NgayDi;
    private com.toedter.calendar.JDateChooser jDateChooser_NgayVe;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel_AirLines;
    private javax.swing.JLabel jLabel_BaoLoi;
    private javax.swing.JLabel jLabel_DangXuat;
    private javax.swing.JLabel jLabel_HPT;
    private javax.swing.JLabel jLabel_HuongDanDatCho;
    private javax.swing.JLabel jLabel_IconMayBay;
    private javax.swing.JLabel jLabel_IconNgayDi;
    private javax.swing.JLabel jLabel_IconNgayVe;
    private javax.swing.JLabel jLabel_NgayDi;
    private javax.swing.JLabel jLabel_NgayVe;
    private javax.swing.JLabel jLabel_NguoiLon;
    private javax.swing.JLabel jLabel_PhanQuyen;
    private javax.swing.JLabel jLabel_QuayLai;
    private javax.swing.JLabel jLabel_SanBayDen;
    private javax.swing.JLabel jLabel_SanBayDi;
    private javax.swing.JLabel jLabel_TenNguoiDung;
    private javax.swing.JLabel jLabel_TreEm;
    private javax.swing.JLabel jLabel_XemThongTinTaiKhoan;
    private javax.swing.JLabel jLabel_XinChao;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel_TaiKhoan;
    private javax.swing.JRadioButton jRadioButton_KhuHoi;
    private javax.swing.JRadioButton jRadioButton_MotChieu;
    // End of variables declaration//GEN-END:variables
}
