package view;

import connection.LoadData;
import connection.UpdateData;
import controller.Controller;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import static javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE;
import javax.swing.table.DefaultTableModel;
import model.HoaDon;
import model.KhachHang;
import model.TaiKhoan;
import model.Ve;

/**
 *
 * @author tuanbuiquoc
 */
public class GiaoDienQuanLyKhachHang extends javax.swing.JFrame {

    /**
     * Creates new form GiaoDienQuanLyKhachHang
     */
    private String sdtKhachHang = "";
    private String maHoaDon = "";

    DefaultTableModel dtmKhachHang = null;
    DefaultTableModel dtmHoaDon = null;
    DefaultTableModel dtmVe = null;

    public GiaoDienQuanLyKhachHang() {
        initComponents();
        jButton_QuayLai.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        jButton_KhoiPhucMK.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        dtmHoaDon = (DefaultTableModel) jTable_HoaDon.getModel();
        dtmHoaDon.setColumnIdentifiers(new Object[]{
            "Mã HĐ", "SĐT KH", "Ngày Xuất", "Thanh Toán", "Tổng", "SĐT NV"
        });

        dtmVe = (DefaultTableModel) jTable_Ve.getModel();
        dtmVe.setColumnIdentifiers(new Object[]{
            "Mã Vé", "Mã CB", "Giá", "Ký Gửi",
            "CMND Người Bay", "Tên Người Bay", "Ngày Sinh", "Mã HĐ", "Mã Ghế"
        });

        dtmKhachHang = (DefaultTableModel) jTable_KhachHang.getModel();
        dtmKhachHang.setColumnIdentifiers(new Object[]{
            "SĐT KH", "Tên KH", "Điểm Tích Lũy"
        });
        loadBangKhachHang();

        this.addWindowListener(new WindowAdapter() {
            public void windowClosing(WindowEvent e) {
                int confirmed = JOptionPane.showConfirmDialog(null,
                        "Bạn có chắc muốn thoát chương trình không?", "Xác nhận",
                        JOptionPane.YES_NO_OPTION);

                if (confirmed == JOptionPane.YES_OPTION) {
                    dispose();
                } else {
                    setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
                }
            }
        });
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);
        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel_IconMayBay = new javax.swing.JLabel();
        jLabel_HPT = new javax.swing.JLabel();
        jLabel_AirLines = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_HoaDon = new javax.swing.JTable(){
            public boolean isCellEditable(int row, int column){
                return false;
            }
        };
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_KhachHang = new javax.swing.JTable(){
            public boolean isCellEditable(int row, int column){
                return false;
            }
        };
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable_Ve = new javax.swing.JTable(){
            public boolean isCellEditable(int row, int column){
                return false;
            }
        };
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField_SDTKhachHang = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField_TenKhachHang = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField_SoHoaDon = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField_SoHoaDonDaThanhToan = new javax.swing.JTextField();
        jTextField_TongTienDaThanhToan = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jButton_QuayLai = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jTextField_TimKiem = new javax.swing.JTextField();
        jCheckBox_HoaDonDaThanhToan = new javax.swing.JCheckBox();
        jLabel10 = new javax.swing.JLabel();
        jButton_KhoiPhucMK = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản lý khách hàng");

        jPanel1.setBackground(new java.awt.Color(48, 57, 82));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        jLabel_IconMayBay.setForeground(new java.awt.Color(204, 255, 255));
        jLabel_IconMayBay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/images/icons8_airplane_48px_4.png"))); // NOI18N

        jLabel_HPT.setFont(new java.awt.Font("Roboto Mono Light", 1, 48)); // NOI18N
        jLabel_HPT.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_HPT.setText("HPT");

        jLabel_AirLines.setFont(new java.awt.Font("Roboto Light", 1, 24)); // NOI18N
        jLabel_AirLines.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_AirLines.setText("AIRLINES™");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel_IconMayBay)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel_HPT)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_AirLines, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel_HPT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel_AirLines, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel_IconMayBay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(89, 98, 117));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });

        jTable_HoaDon.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jTable_HoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable_HoaDon.setRowHeight(25);
        jTable_HoaDon.setRowMargin(2);
        jTable_HoaDon.setSelectionBackground(new java.awt.Color(255, 77, 77));
        jTable_HoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_HoaDonMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_HoaDon);

        jTable_KhachHang.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jTable_KhachHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable_KhachHang.setRowHeight(25);
        jTable_KhachHang.setRowMargin(2);
        jTable_KhachHang.setSelectionBackground(new java.awt.Color(255, 77, 77));
        jTable_KhachHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_KhachHangMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable_KhachHang);

        jTable_Ve.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jTable_Ve.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable_Ve.setRowHeight(25);
        jTable_Ve.setRowMargin(2);
        jTable_Ve.setSelectionBackground(new java.awt.Color(255, 77, 77));
        jScrollPane3.setViewportView(jTable_Ve);

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Danh Sách Khách Hàng");

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Hóa Đơn Tương Ứng");

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("SĐT Khách hàng");

        jLabel4.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Vé Trong Hóa Đơn Đã Chọn");

        jTextField_SDTKhachHang.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField_SDTKhachHang.setEnabled(false);

        jLabel5.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Tên Khách Hàng");

        jTextField_TenKhachHang.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField_TenKhachHang.setEnabled(false);

        jLabel6.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Số Hóa Đơn");

        jTextField_SoHoaDon.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField_SoHoaDon.setEnabled(false);

        jLabel7.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Số Hóa Đơn Đã Thanh Toán");

        jTextField_SoHoaDonDaThanhToan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField_SoHoaDonDaThanhToan.setEnabled(false);

        jTextField_TongTienDaThanhToan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField_TongTienDaThanhToan.setEnabled(false);

        jLabel8.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Tổng Tiền Đã Thanh Toán");

        jButton_QuayLai.setBackground(new java.awt.Color(0, 102, 102));
        jButton_QuayLai.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        jButton_QuayLai.setForeground(new java.awt.Color(255, 255, 255));
        jButton_QuayLai.setText("Quay Lại");
        jButton_QuayLai.setBorderPainted(false);
        jButton_QuayLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_QuayLaiActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Thông tin cơ bản của khách đã chọn");

        jTextField_TimKiem.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_TimKiemFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_TimKiemFocusLost(evt);
            }
        });
        jTextField_TimKiem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_TimKiemKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_TimKiemKeyTyped(evt);
            }
        });

        jCheckBox_HoaDonDaThanhToan.setBackground(new java.awt.Color(89, 98, 117));
        jCheckBox_HoaDonDaThanhToan.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jCheckBox_HoaDonDaThanhToan.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox_HoaDonDaThanhToan.setText("Đã thanh toán");
        jCheckBox_HoaDonDaThanhToan.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBox_HoaDonDaThanhToanItemStateChanged(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("| Tìm theo SĐT");

        jButton_KhoiPhucMK.setBackground(new java.awt.Color(255, 77, 77));
        jButton_KhoiPhucMK.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        jButton_KhoiPhucMK.setForeground(java.awt.Color.white);
        jButton_KhoiPhucMK.setText("Khôi phục MK");
        jButton_KhoiPhucMK.setBorderPainted(false);
        jButton_KhoiPhucMK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_KhoiPhucMKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 872, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(1, 1, 1)
                                    .addComponent(jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel10)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextField_TimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel8)
                                    .addComponent(jButton_QuayLai, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(56, 56, 56)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField_TongTienDaThanhToan)
                                    .addComponent(jTextField_TenKhachHang)
                                    .addComponent(jTextField_SoHoaDon)
                                    .addComponent(jTextField_SDTKhachHang, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                                    .addComponent(jTextField_SoHoaDonDaThanhToan)
                                    .addComponent(jButton_KhoiPhucMK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel4)
                                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jCheckBox_HoaDonDaThanhToan)))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jTextField_TimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox_HoaDonDaThanhToan)
                    .addComponent(jLabel10))
                .addGap(1, 1, 1)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel9))
                        .addGap(3, 3, 3)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextField_SDTKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTextField_TenKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jTextField_SoHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jTextField_SoHoaDonDaThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_TongTienDaThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_QuayLai, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_KhoiPhucMK))
                .addContainerGap())
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButton_KhoiPhucMK, jButton_QuayLai});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void loadBangKhachHang() {
        dtmKhachHang.setRowCount(0);
        new LoadData();
        for (KhachHang kh : controller.Controller.arrayListKhachHang) {
            dtmKhachHang.addRow(new Object[]{
                kh.getSdtKhachHang(), kh.getTenKhachHang(),
                kh.getDiemTichLuy()
            });
        }
    }
    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel2MousePressed

    private void loadBangHoaDonTheoSDTKhachHang() {
        new LoadData();
        dtmHoaDon.setRowCount(0);
        for (KhachHang kh : controller.Controller.arrayListKhachHang) {
            if (kh.getSdtKhachHang().equals(this.sdtKhachHang)) {
                jTextField_SDTKhachHang.setText(kh.getSdtKhachHang());
                jTextField_TenKhachHang.setText(kh.getTenKhachHang());
                int soHoaDon = 0;
                int soHoaDonDaThanhToan = 0;
                int tongTienDaThanhToan = 0;

                for (HoaDon hd : controller.Controller.arrayListHoaDon) {
                    if (hd.getSdtKhachHang().equals(this.sdtKhachHang)) {
                        dtmHoaDon.addRow(new Object[]{
                            hd.getMaHoaDon(), hd.getSdtKhachHang(), new SimpleDateFormat("dd/MM/yyyy").format(hd.getNgayXuatHoaDon()),
                            hd.getTrangThaiThanhToan(), hd.getTongTien(), hd.getSdtNhanVien()
                        });
                        soHoaDon++;
                        if (hd.getTrangThaiThanhToan() == 1) {
                            soHoaDonDaThanhToan++;
                            tongTienDaThanhToan = tongTienDaThanhToan + hd.getTongTien();
                        }

                    }

                }
                jTextField_SoHoaDon.setText(soHoaDon + "");
                jTextField_SoHoaDonDaThanhToan.setText(soHoaDonDaThanhToan + "");
                jTextField_TongTienDaThanhToan.setText(tongTienDaThanhToan + "");
            }
        }
    }

    private void clearTextFieldThongTinKhachHang() {
        jTextField_SDTKhachHang.setText("");
        jTextField_TenKhachHang.setText("");
        jTextField_SoHoaDon.setText("0");
        jTextField_TongTienDaThanhToan.setText("0");
        jTextField_SoHoaDonDaThanhToan.setText("0");
    }

    private void jTable_KhachHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_KhachHangMouseClicked
        // TODO add your handling code here:
        int row = jTable_KhachHang.getSelectedRow();

        if (row == -1) {

        } else {
            this.sdtKhachHang = (String) jTable_KhachHang.getValueAt(row, 0);
            System.out.println("SDT của khách đã chọn: " + this.sdtKhachHang);
            if (jCheckBox_HoaDonDaThanhToan.isSelected()) {
                loadBangHoaDonDaThanhToanTheoSDTKhachHang();
            } else {
                loadBangHoaDonTheoSDTKhachHang();
            }

        }
    }//GEN-LAST:event_jTable_KhachHangMouseClicked

    private void jTable_HoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_HoaDonMouseClicked
        // TODO add your handling code here:
        int row = jTable_HoaDon.getSelectedRow();
        if (row == -1) {
        } else {
            String maHoaDon = (String) jTable_HoaDon.getValueAt(row, 0);
            new LoadData();
            dtmVe.setRowCount(0);
            for (Ve v : controller.Controller.arrayListVe) {
                if (v.getMaHoaDon().equals(maHoaDon)) {
                    if (v.getNgaySinh() != null) {
                        dtmVe.addRow(new Object[]{
                            v.getMaVe(), v.getMaChuyenBay(), v.getGia(), v.getKyGui(),
                            v.getCmndNguoiBay(), v.getTenNguoiBay(), new SimpleDateFormat("dd/MM/yyyy").format(v.getNgaySinh()),
                            v.getMaHoaDon(), v.getMaGhe()
                        });
                    } else {
                        dtmVe.addRow(new Object[]{
                            v.getMaVe(), v.getMaChuyenBay(), v.getGia(), v.getKyGui(),
                            v.getCmndNguoiBay(), v.getTenNguoiBay(), "",
                            v.getMaHoaDon(), v.getMaGhe()
                        });
                    }
                }
            }
        }
    }//GEN-LAST:event_jTable_HoaDonMouseClicked

    private void jButton_QuayLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_QuayLaiActionPerformed
        // TODO add your handling code here:
        this.dispose();

        new GiaoDienQuanLy().setVisible(true);

    }//GEN-LAST:event_jButton_QuayLaiActionPerformed

    private void jTextField_TimKiemKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_TimKiemKeyReleased
        // TODO add your handling code here:
        clearTextFieldThongTinKhachHang();
        if (jTextField_TimKiem.getText().length() >= 11) {
            jTextField_TimKiem.setText(jTextField_TimKiem.getText().substring(0, jTextField_TimKiem.getText().length() - 1));
        } else {
            dtmKhachHang.setRowCount(0);
            new LoadData();
            int length = jTextField_TimKiem.getText().length();
            for (KhachHang kh : controller.Controller.arrayListKhachHang) {
                if (kh.getSdtKhachHang().contains(jTextField_TimKiem.getText().trim())) {
                    dtmKhachHang.addRow(new Object[]{
                        kh.getSdtKhachHang(), kh.getTenKhachHang(),
                        kh.getDiemTichLuy()
                    });
                }
            }
            if (jTextField_TimKiem.getText().isEmpty()) {
                loadBangKhachHang();
            }
        }

    }//GEN-LAST:event_jTextField_TimKiemKeyReleased

    private void jTextField_TimKiemFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_TimKiemFocusGained
        // TODO add your handling code here:
        if (jTextField_TimKiem.getText().equals("Tìm khách theo sđt")) {
            jTextField_TimKiem.setText("");
            jTextField_TimKiem.setForeground(Color.black);
        }
    }//GEN-LAST:event_jTextField_TimKiemFocusGained

    private void jTextField_TimKiemFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_TimKiemFocusLost
        // TODO add your handling code here:
        if (jTextField_TimKiem.getText().isEmpty()) {
            jTextField_TimKiem.setText("Tìm khách theo sđt");
            jTextField_TimKiem.setForeground(Color.gray);
        }
    }//GEN-LAST:event_jTextField_TimKiemFocusLost

    private void loadBangHoaDonDaThanhToanTheoSDTKhachHang() {
        new LoadData();
        dtmHoaDon.setRowCount(0);
        for (KhachHang kh : controller.Controller.arrayListKhachHang) {
            if (kh.getSdtKhachHang().equals(this.sdtKhachHang)) {
                jTextField_SDTKhachHang.setText(kh.getSdtKhachHang());
                jTextField_TenKhachHang.setText(kh.getTenKhachHang());
                int soHoaDon = 0;
                int soHoaDonDaThanhToan = 0;
                int tongTienDaThanhToan = 0;

                for (HoaDon hd : controller.Controller.arrayListHoaDon) {
                    if (hd.getSdtKhachHang().equals(this.sdtKhachHang) && hd.getTrangThaiThanhToan() == 1) {
                        dtmHoaDon.addRow(new Object[]{
                            hd.getMaHoaDon(), hd.getSdtKhachHang(), new SimpleDateFormat("dd/MM/yyyy").format(hd.getNgayXuatHoaDon()),
                            hd.getTrangThaiThanhToan(), hd.getTongTien(), hd.getSdtNhanVien()
                        });
                        soHoaDon++;
                        if (hd.getTrangThaiThanhToan() == 1) {
                            soHoaDonDaThanhToan++;
                            tongTienDaThanhToan = tongTienDaThanhToan + hd.getTongTien();
                        }

                    }

                }
                jTextField_SoHoaDon.setText(soHoaDon + "");
                jTextField_SoHoaDonDaThanhToan.setText(soHoaDonDaThanhToan + "");
                jTextField_TongTienDaThanhToan.setText(tongTienDaThanhToan + "");
            }
        }
    }
    private void jCheckBox_HoaDonDaThanhToanItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBox_HoaDonDaThanhToanItemStateChanged
        // TODO add your handling code here:
        int row = jTable_KhachHang.getSelectedRow();

        if (row == -1) {

        } else {
            this.sdtKhachHang = (String) jTable_KhachHang.getValueAt(row, 0);
            System.out.println("SDT của khách đã chọn: " + this.sdtKhachHang);
            if (jCheckBox_HoaDonDaThanhToan.isSelected()) {
                loadBangHoaDonDaThanhToanTheoSDTKhachHang();
            } else {
                loadBangHoaDonTheoSDTKhachHang();
            }

        }

    }//GEN-LAST:event_jCheckBox_HoaDonDaThanhToanItemStateChanged

    private void jTextField_TimKiemKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_TimKiemKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_TimKiemKeyTyped

    private void jButton_KhoiPhucMKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_KhoiPhucMKActionPerformed
        if (jTable_KhachHang.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(null, "Bạn vui chọn khách hàng cần khôi phục mật khẩu");
            return;
        }
        int confirm = JOptionPane.showConfirmDialog(null,
                "Mật khẩu sẽ được khôi phục thành 123. Bạn có chắc chắn muốn khôi phục?");
        if (confirm == JOptionPane.YES_OPTION) {
            TaiKhoan taiKhoan = null;
            int vt = 0;
            for (TaiKhoan tk : Controller.arrayListTaiKhoan) {
                if (tk.getSdt().equals(sdtKhachHang)) {
                    taiKhoan = tk;
                    break;
                }
                vt++;
            }
            taiKhoan.setMatKhau("123");
            Controller.arrayListTaiKhoan.set(vt, taiKhoan);
            UpdateData.updateTaiKhoan(taiKhoan);
            JOptionPane.showMessageDialog(null, "Mật khẩu đã được khôi phục");
        }
    }//GEN-LAST:event_jButton_KhoiPhucMKActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GiaoDienQuanLyKhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GiaoDienQuanLyKhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GiaoDienQuanLyKhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GiaoDienQuanLyKhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GiaoDienQuanLyKhachHang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_KhoiPhucMK;
    private javax.swing.JButton jButton_QuayLai;
    private javax.swing.JCheckBox jCheckBox_HoaDonDaThanhToan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_AirLines;
    private javax.swing.JLabel jLabel_HPT;
    private javax.swing.JLabel jLabel_IconMayBay;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTable jTable_HoaDon;
    private javax.swing.JTable jTable_KhachHang;
    private javax.swing.JTable jTable_Ve;
    private javax.swing.JTextField jTextField_SDTKhachHang;
    private javax.swing.JTextField jTextField_SoHoaDon;
    private javax.swing.JTextField jTextField_SoHoaDonDaThanhToan;
    private javax.swing.JTextField jTextField_TenKhachHang;
    private javax.swing.JTextField jTextField_TimKiem;
    private javax.swing.JTextField jTextField_TongTienDaThanhToan;
    // End of variables declaration//GEN-END:variables
}
